// <auto-generated />
namespace IT_Heaven.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FavoritesDataModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FavoritesDataModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705020907343_FavoritesDataModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
